package yggdrasil.psi

import com.intellij.psi.tree.IElementType
import com.intellij.psi.tree.TokenSet

object YggdrasilTypes {
    // Comment tokens
    val COMMENT_LINE: IElementType = YggdrasilTokenType("COMMENT_LINE")
    val COMMENT_BLOCK: IElementType = YggdrasilTokenType("COMMENT_BLOCK")

    // Literal tokens
    val URL: IElementType = YggdrasilTokenType("URL")
    val SYMBOL: IElementType = YggdrasilTokenType("SYMBOL")
    val ESCAPED: IElementType = YggdrasilTokenType("ESCAPED")
    val INTEGER: IElementType = YggdrasilTokenType("INTEGER")
    val REFERENCE: IElementType = YggdrasilTokenType("REFERENCE")
    val SELECTION_LINE: IElementType = YggdrasilTokenType("SELECTION_LINE")

    // Keyword tokens
    val KW_GRAMMAR: IElementType = YggdrasilTokenType("KW_GRAMMAR")
    val KW_USING: IElementType = YggdrasilTokenType("KW_USING")
    val KW_GROUP: IElementType = YggdrasilTokenType("KW_GROUP")
    val KW_CLASS: IElementType = YggdrasilTokenType("KW_CLASS")
    val KW_UNION: IElementType = YggdrasilTokenType("KW_UNION")
    val KW_CLIMB: IElementType = YggdrasilTokenType("KW_CLIMB")
    val KW_IMPORT: IElementType = YggdrasilTokenType("KW_IMPORT")
    val KW_AS: IElementType = YggdrasilTokenType("KW_AS")
    val KW_MACRO: IElementType = YggdrasilTokenType("KW_MACRO")
    val KW_OPERATORS: IElementType = YggdrasilTokenType("KW_OPERATORS")

    // Punctuation tokens
    val PARENTHESIS_L: IElementType = YggdrasilTokenType("PARENTHESIS_L")
    val PARENTHESIS_R: IElementType = YggdrasilTokenType("PARENTHESIS_R")
    val BRACKET_L: IElementType = YggdrasilTokenType("BRACKET_L")
    val BRACKET_R: IElementType = YggdrasilTokenType("BRACKET_R")
    val BRACE_L: IElementType = YggdrasilTokenType("BRACE_L")
    val BRACE_R: IElementType = YggdrasilTokenType("BRACE_R")
    val ANGLE_L: IElementType = YggdrasilTokenType("ANGLE_L")
    val ANGLE_R: IElementType = YggdrasilTokenType("ANGLE_R")
    val OP_REMARK: IElementType = YggdrasilTokenType("OP_REMARK")
    val BIND: IElementType = YggdrasilTokenType("BIND")
    val COLON: IElementType = YggdrasilTokenType("COLON")
    val SEMICOLON: IElementType = YggdrasilTokenType("SEMICOLON")
    val COMMA: IElementType = YggdrasilTokenType("COMMA")
    val DOLLAR: IElementType = YggdrasilTokenType("DOLLAR")
    val DOT: IElementType = YggdrasilTokenType("DOT")
    val OP_MANY: IElementType = YggdrasilTokenType("OP_MANY")
    val AT: IElementType = YggdrasilTokenType("AT")
    val TO: IElementType = YggdrasilTokenType("TO")
    val HYPHEN: IElementType = YggdrasilTokenType("HYPHEN")
    val SLASH: IElementType = YggdrasilTokenType("SLASH")
    val OP_OR: IElementType = YggdrasilTokenType("OP_OR")
    val OP_CONCAT: IElementType = YggdrasilTokenType("OP_CONCAT")
    val PLACE_HOLDER: IElementType = YggdrasilTokenType("PLACE_HOLDER")
    val HASH: IElementType = YggdrasilTokenType("HASH")
    val OP_NOT: IElementType = YggdrasilTokenType("OP_NOT")
    val OP_OPTIONAL: IElementType = YggdrasilTokenType("OP_OPTIONAL")
    val OP_MANY1: IElementType = YggdrasilTokenType("OP_MANY1")
    val TEXT_SINGLE: IElementType = YggdrasilTokenType("TEXT_SINGLE")
    val TEXT_DOUBLE: IElementType = YggdrasilTokenType("TEXT_DOUBLE")
    val REGULAR_EXPRESSION: IElementType = YggdrasilTokenType("REGULAR_EXPRESSION")
    val REGULAR_RANGE: IElementType = YggdrasilTokenType("REGULAR_RANGE")
    val SYMBOW_RAW: IElementType = YggdrasilTokenType("SYMBOW_RAW")

    // Element types
    val ANNOTATIONS: IElementType = YggdrasilElementType("ANNOTATIONS")
    val MODIFIER: IElementType = YggdrasilElementType("MODIFIER")
    val ATTRIBUTE: IElementType = YggdrasilElementType("ATTRIBUTE")
    val GRAMMAR: IElementType = YggdrasilElementType("GRAMMAR")
    val GRAMMAR_INHERIT: IElementType = YggdrasilElementType("GRAMMAR_INHERIT")
    val GRAMMAR_BODY: IElementType = YggdrasilElementType("GRAMMAR_BODY")
    val GRAMMAR_TERM: IElementType = YggdrasilElementType("GRAMMAR_TERM")
    val USING: IElementType = YggdrasilElementType("USING")
    val USING_BODY: IElementType = YggdrasilElementType("USING_BODY")
    val USING_TERM: IElementType = YggdrasilElementType("USING_TERM")
    val USING_ALIAS: IElementType = YggdrasilElementType("USING_ALIAS")
    val DEFINE_CLASS: IElementType = YggdrasilElementType("DEFINE_CLASS")
    val CLASS_CAST: IElementType = YggdrasilElementType("CLASS_CAST")
    val CLASS_BODY: IElementType = YggdrasilElementType("CLASS_BODY")
    val DEFINE_UNION: IElementType = YggdrasilElementType("DEFINE_UNION")
    val UNION_BODY: IElementType = YggdrasilElementType("UNION_BODY")
    val UNION_VARIANT: IElementType = YggdrasilElementType("UNION_VARIANT")
    val TAG_BRANCH: IElementType = YggdrasilElementType("TAG_BRANCH")
    val GROUP: IElementType = YggdrasilElementType("GROUP")
    val GROUP_BODY: IElementType = YggdrasilElementType("GROUP_BODY")
    val GROUP_TERM: IElementType = YggdrasilElementType("GROUP_TERM")
    val GROUP_ITEM: IElementType = YggdrasilElementType("GROUP_ITEM")
    val OPERATORS: IElementType = YggdrasilElementType("OPERATORS")
    val DEFINE_FUNCTION: IElementType = YggdrasilElementType("DEFINE_FUNCTION")
    val FUNCTION_PARAMETER: IElementType = YggdrasilElementType("FUNCTION_PARAMETER")
    val PARAMETER: IElementType = YggdrasilElementType("PARAMETER")
    val FUNCTION_BLOCK: IElementType = YggdrasilElementType("FUNCTION_BLOCK")
    val FUNCTION_CALL: IElementType = YggdrasilElementType("FUNCTION_CALL")
    val EXPRESSION: IElementType = YggdrasilElementType("EXPRESSION")
    val EXPRESSION_CHOICE: IElementType = YggdrasilElementType("EXPRESSION_CHOICE")
    val EXPRESSION_HARD: IElementType = YggdrasilElementType("EXPRESSION_HARD")
    val EXPRESSION_SOFT: IElementType = YggdrasilElementType("EXPRESSION_SOFT")
    val EXPRESSION_TAG: IElementType = YggdrasilElementType("EXPRESSION_TAG")
    val TERM: IElementType = YggdrasilElementType("TERM")
    val PREFIX: IElementType = YggdrasilElementType("PREFIX")
    val SUFFIX: IElementType = YggdrasilElementType("SUFFIX")
    val ATOMIC: IElementType = YggdrasilElementType("ATOMIC")
    val EXPRESSION_GROUP: IElementType = YggdrasilElementType("EXPRESSION_GROUP")
    val ESCAPE: IElementType = YggdrasilElementType("ESCAPE")
    val CATEGORY: IElementType = YggdrasilElementType("CATEGORY")
    val RANGE: IElementType = YggdrasilElementType("RANGE")
    val RANGE_LOWER: IElementType = YggdrasilElementType("RANGE_LOWER")
    val RANGE_UPPER: IElementType = YggdrasilElementType("RANGE_UPPER")
    val STRING: IElementType = YggdrasilElementType("STRING")
    val REGEX: IElementType = YggdrasilElementType("REGEX")
    val KEY: IElementType = YggdrasilElementType("KEY")
    val VALUE: IElementType = YggdrasilElementType("VALUE")
    val PAIR: IElementType = YggdrasilElementType("PAIR")
    val ARGUMENT: IElementType = YggdrasilElementType("ARGUMENT")
    val TUPLE: IElementType = YggdrasilElementType("TUPLE")
    val NUMBER: IElementType = YggdrasilElementType("NUMBER")
    val IDENTIFIER: IElementType = YggdrasilElementType("IDENTIFIER")

    // Token sets
    val COMMENT_TOKENS: TokenSet = TokenSet.create(COMMENT_LINE, COMMENT_BLOCK)
    val WHITESPACE_TOKENS: TokenSet = TokenSet.create(com.intellij.psi.TokenType.WHITE_SPACE)
    val STRING_LITERAL_TOKENS: TokenSet = TokenSet.create(TEXT_SINGLE, TEXT_DOUBLE)

    // Factory object for creating elements
    object Factory {
        fun createElement(node: com.intellij.lang.ASTNode): com.intellij.psi.PsiElement {
            return yggdrasil.psi.YggdrasilElement(node)
        }
    }
}